name: pp_14_copy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  in_app_review: ^2.0.8
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  flutter_svg: ^2.0.9
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  path_drawing: ^1.0.1
  path: ^1.8.3
  flutter_app_info: ^2.0.0
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  bloc: ^8.1.2
  hive: ^2.2.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  http: ^1.2.0
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.18+3
  mask_text_input_formatter: ^2.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_remote_config: ^4.3.8
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter_android: ^3.15.0
  webview_flutter: ^4.5.0
  cached_network_image: ^3.3.1
  adaptive_dialog: ^2.1.0

  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/